language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
language: rust
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cd xray_core && cargo test --verbose --all
